version: '3.9'
services:
  react-app:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  github-runner:
    build:
      context: ./frontend/actions-runner
      dockerfile: Dockerfile.runner
    environment:
      - REPO_URL
      - RUNNER_TOKEN
      - RUNNER_NAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    user: root
    restart: always

# version: '3.8'
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3001:3000"
#     volumes:
#       - ./:/frontend
#       - /frontend/node_modules    
#     working_dir: /frontend
#     environment:
#       - NODE_ENV=development
#       - WDS_SOCKET_PORT=0
#       - REACT_APP_WDS_SOCKET_PORT=0
#     stdin_open: true
#     tty: true
#     develop:
#       watch:
#         - action: sync
#           path: ./
#           target: /frontend
#           ignore:
#             - node_modules/
#         - action: rebuild
#           path: ./package.json