
name: Local Deploy CI/CD

on:
  push:
    branches:
      - main  # Puedes cambiar a la rama que quieras

jobs:
  deploy:
    runs-on: self-hosted  # Muy importante: esto le dice que corra en tu runner local
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker-compose build --no-cache

      - name: Deploy containers
        run: docker-compose up -d --force-recreate

      - name: Cleanup unused images
        run: docker image prune -f

