name: Local Deploy CI/CD

on:
  push:
    branches:
      - main  # Puedes cambiar a la rama que quieras

jobs:
  deploy:
    runs-on: self-hosted  # Muy importante: esto le dice que corra en tu runner local
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run: docker compose build react-app

      - name: Restart Frontend Container
        run: docker compose up -d react-app

