name: Deploy to Local Server

on:
  push:
    branches:
      - main  # <- ajusta si tu rama es otra

jobs:
  deploy:
    runs-on: [self-hosted, linux, docker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Latest Code and Rebuild Container
        run: |
          cd /home/lnxadmin/ci-runners  # <-- Ruta donde está tu docker-compose.yml en el servidor
          echo "📦 Pulling latest changes from main branch..."
          git pull origin main
          
          echo "🚀 Stopping existing containers..."
          docker-compose down

          echo "🔨 Building new Docker images..."
          docker-compose build --no-cache

          echo "🚀 Starting updated containers..."
          docker-compose up -d

      - name: Cleanup Dangling Images (Optional)
        run: docker image prune -f
