name: Deploy to Local Server

on:
  push:
    branches:
      - main  # <- ajusta si tu rama es otra

jobs:
  deploy:
    runs-on: [self-hosted, linux, docker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy Containers
        run: |
          cd /home/lnxadmin/ci-runners

          echo "Stopping existing containers..."
          docker compose down

          echo "Starting new containers..."
          docker compose up --build -d

      - name: Clean up dangling images
        run: docker image prune -f
