name: Local Deploy CI/CD

on:
  push:
    branches:
      - main  # Puedes cambiar a la rama que quieras

jobs:
  deploy:
    runs-on: self-hosted  # Muy importante: esto le dice que corra en tu runner local
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Docker Compose Version
        run: |
          which docker
          docker version
          docker compose version
          docker compose build --help

      - name: Build Docker Compose (no cache)
        run: docker compose -f frontend/docker-compose.yml build --no-cache


      - name: Deploy containers
        run: docker compose up -d --force-recreate

      - name: Cleanup unused images
        run: docker image prune -f

